export const animalInfos = [
  {name: 'Chicken', winRate: 90},
  {name: 'Duck', winRate: 90},
  {name: 'Rabbit', winRate: 90},
  {name: 'Toucan', winRate: 85},
  {name: 'Hyena', winRate: 80},
  {name: 'Penguin', winRate: 76},
  {name: 'Fox', winRate: 72},
  {name: 'Goat', winRate: 68},
  {name: 'Sheep', winRate: 64},
  {name: 'Pig', winRate: 60},
  {name: 'Panda', winRate: 58},
  {name: 'Cow', winRate: 56},
  {name: 'Horse', winRate: 54},
  {name: 'Golden Eagle', winRate: 52},
  {name: 'Boar', winRate: 50},
  {name: 'Deer', winRate: 50},
  {name: 'Camel', winRate: 50},
  {name: 'Bull', winRate: 50},
  {name: 'Leopard', winRate: 50},
  {name: 'Cocodrile', winRate: 50},
  {name: 'Zebra', winRate: 50},
  {name: 'Longhorn Cattle', winRate: 50},
  {name: 'Tiger', winRate: 50},
  {name: 'Comodo Dragon', winRate: 50},
  {name: 'Buffalo', winRate: 50},
  {name: 'Lion', winRate: 50},
  {name: 'Bear', winRate: 50},
  {name: 'Hippopotamus', winRate: 50},
  {name: 'Rhino', winRate: 50},
  {name: 'Elephant', winRate: 50},
]
